uc_check.settings:
  type: mapping
  label: 'Check payment method settings'
  mapping:
    policy:
      type: string
      label: 'Check payment policy message'
    mailing_name:
      type: string
      label: ''
    mailing_company:
      type: string
      label: ''
    mailing_street1:
      type: string
      label: ''
    mailing_street2:
      type: string
      label: ''
    mailing_city:
      type: string
      label: ''
    mailing_zone:
      type: string
      label: ''
    mailing_postal_code:
      type: string
      label: ''
    mailing_country:
      type: int
      label: ''

uc_cod.settings:
  type: mapping
  label: 'COD payment method settings'
  mapping:
    policy:
      type: string
      label: 'COD payment policy message'
    max_order:
      type: float
      label: ''
    delivery_date:
      type: boolean
      label: ''
