uc_order.status.*:
  type: config_entity
  label: 'Order status'
  mapping:
    id:
      type: string
      label: 'ID'
    name:
      type: label
      label: 'Name'
    state:
      type: string
      label: 'Order state'
    weight:
      type: integer
      label: 'Weight'
    locked:
      type: boolean
      label: 'Locked'
    status:
      type: boolean
      label: 'Status'
    langcode:
      type: string
      label: 'Default language'
