name: uc_thumbnail
label: 'Product (thumbnail)'
effects:
  c6c0890c-4496-48cc-9205-5c3b4e8148aa:
    id: image_scale
    data:
      width: '35'
      height: '35'
      upscale: '0'
    weight: '1'
    uuid: c6c0890c-4496-48cc-9205-5c3b4e8148aa
langcode: en
