api_version: '3.0'
base_field: nid
base_table: node
core: 8.x
description: ''
disabled: '0'
display:
  default:
    display_plugin: default
    id: default
    display_title: Master
    position: ''
    display_options:
      access:
        type: perm
        options:
          perm: 'administer products'
      cache:
        type: none
      query:
        type: views_query
      exposed_form:
        type: basic
      pager:
        type: full
        options:
          items_per_page: '50'
      style:
        type: table
        options:
          grouping: {  }
          row_class: ''
          default_row_class: '1'
          row_class_special: '1'
          override: '1'
          sticky: '0'
          summary: ''
          columns:
            title: title
            display_price: display_price
            changed: changed
          info:
            title:
              sortable: '1'
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: '0'
              responsive: ''
            display_price:
              sortable: '1'
              default_sort_order: desc
              align: ''
              separator: ''
              empty_column: '0'
              responsive: ''
            changed:
              sortable: '1'
              default_sort_order: desc
              align: ''
              separator: ''
              empty_column: '0'
              responsive: ''
          default: changed
          empty_table: '0'
      row:
        type: node
        options:
          build_mode: teaser
          links: '1'
          comments: '0'
      fields:
        title:
          id: title
          table: node_field_data
          field: title
          relationship: none
          group_type: group
          admin_label: ''
          label: Title
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '0'
            ellipsis: '0'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          link_to_node: '1'
        display_price:
          id: display_price
          table: uc_products
          field: display_price
          relationship: none
          group_type: group
          admin_label: ''
          label: Price
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          set_precision: '0'
          precision: '0'
          decimal: .
          separator: ','
          format_plural: '0'
          format_plural_singular: '1'
          format_plural_plural: '@count'
          prefix: ''
          suffix: ''
          format: uc_price
        changed:
          id: changed
          table: node_field_data
          field: changed
          relationship: none
          group_type: group
          admin_label: ''
          label: Updated
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          date_format: short
          custom_date_format: ''
          timezone: ''
      filters:
        status:
          value: '1'
          table: node_field_data
          field: status
          id: status
          expose:
            operator: '0'
          group: '1'
        is_product:
          id: is_product
          table: uc_products
          field: is_product
          relationship: none
          group_type: group
          admin_label: ''
          operator: '='
          value: '1'
          group: '1'
          exposed: '0'
          expose:
            operator_id: '0'
            label: ''
            description: ''
            use_operator: '0'
            operator: ''
            identifier: ''
            required: '0'
            remember: '0'
            multiple: '0'
            remember_roles:
              authenticated: authenticated
          is_grouped: '0'
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: '1'
            widget: select
            multiple: '0'
            remember: '0'
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
        title:
          id: title
          table: node_field_data
          field: title
          relationship: none
          group_type: group
          admin_label: ''
          operator: contains
          value: ''
          group: '1'
          exposed: '1'
          expose:
            operator_id: title_op
            label: Title
            description: ''
            use_operator: '0'
            operator: title_op
            identifier: title
            required: '0'
            remember: '0'
            multiple: '0'
            remember_roles:
              authenticated: authenticated
              anonymous: '0'
              administrator: '0'
          is_grouped: '0'
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: '1'
            widget: select
            multiple: '0'
            remember: '0'
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
      sorts: {  }
      title: Products
  admin_page:
    display_plugin: page
    id: admin_page
    display_title: Page
    position: ''
    display_options:
      path: admin/store/products/view
      menu:
        type: normal
        title: 'View products'
        description: 'View and search products available through your website.'
        name: admin
        weight: '-10'
        context: '0'
    new_id: admin_page
human_name: Products
id: uc_products
module: uc_product
tag: Ubercart
