uc_country.formats:
  type: mapping
  label: 'Country address formats'
  mapping:
    840:
      type: string
      label: 'US address format string'
    124:
      type: string
      label: 'Canada address format string'
