base_field: uid
base_table: users
core: 8.x
description: ''
status: true
display:
  default:
    display_plugin: default
    id: default
    display_title: Master
    position: 1
    display_options:
      access:
        type: perm
        options:
          perm: 'access content'
        perm: 'access user profiles'
      cache:
        type: none
        options: {  }
      query:
        type: views_query
        options:
          disable_sql_rewrite: false
          distinct: false
          slave: false
          query_comment: ''
          query_tags: {  }
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: false
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: true
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        type: full
        options:
          items_per_page: '30'
          offset: 0
          id: 0
          total_pages: ''
          expose:
            items_per_page: false
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 20, 40, 60'
            items_per_page_options_all: false
            items_per_page_options_all_label: '- All -'
            offset: false
            offset_label: Offset
          tags:
            previous: '‹ previous'
            next: 'next ›'
            first: '« first'
            last: 'last »'
          quantity: 9
      style:
        type: table
        options:
          grouping: {  }
          row_class: ''
          default_row_class: 1
          row_class_special: 1
          override: 1
          sticky: 0
          caption: ''
          summary: ''
          description: ''
          columns:
            uid: uid
            name: name
            billing_full_name: billing_full_name
            primary_email: primary_email
            billing_city: billing_city
            zone_code: billing_city
            country_name: billing_city
            order_id: order_id
            order_total: order_total
          info:
            uid:
              sortable: 0
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: 0
              responsive: ''
            name:
              sortable: 1
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: 0
              responsive: ''
            billing_full_name:
              sortable: 0
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: 0
              responsive: ''
            primary_email:
              sortable: 1
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: 0
              responsive: ''
            billing_city:
              sortable: 1
              default_sort_order: asc
              align: ''
              separator: ', '
              empty_column: 0
              responsive: ''
            zone_code:
              sortable: 0
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: 0
              responsive: ''
            country_name:
              sortable: 0
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: 0
              responsive: ''
            order_id:
              sortable: 1
              default_sort_order: desc
              align: ''
              separator: ''
              empty_column: 0
              responsive: ''
            order_total:
              sortable: 1
              default_sort_order: desc
              align: ''
              separator: ''
              empty_column: 0
              responsive: ''
          default: order_id
          empty_table: 0
      row:
        type: fields
      fields:
        uid:
          id: uid
          table: users
          field: uid
          relationship: none
          group_type: group
          admin_label: ''
          label: ''
          exclude: 1
          alter:
            alter_text: 0
            text: ''
            make_link: 0
            path: ''
            absolute: 0
            external: 0
            replace_spaces: 0
            path_case: none
            trim_whitespace: 0
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: 0
            max_length: ''
            word_boundary: 1
            ellipsis: 1
            more_link: 0
            more_link_text: ''
            more_link_path: ''
            strip_tags: 0
            trim: 0
            preserve_tags: ''
            html: 0
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: false
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: 1
          empty: ''
          hide_empty: 0
          empty_zero: 0
          hide_alter_empty: 1
          link_to_user: 0
          plugin_id: user
          provider: user
        name:
          id: name
          table: users
          field: name
          relationship: none
          group_type: group
          admin_label: ''
          label: User
          exclude: 0
          alter:
            alter_text: 0
            text: ''
            make_link: 0
            path: ''
            absolute: 0
            external: 0
            replace_spaces: 0
            path_case: none
            trim_whitespace: 0
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: 0
            max_length: ''
            word_boundary: 0
            ellipsis: 0
            more_link: 0
            more_link_text: ''
            more_link_path: ''
            strip_tags: 0
            trim: 0
            preserve_tags: ''
            html: 0
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: 1
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: 1
          empty: ''
          hide_empty: 0
          empty_zero: 0
          hide_alter_empty: 1
          link_to_user: 1
          overwrite_anonymous: 0
          anonymous_text: ''
          format_username: 1
          provider: user
        billing_full_name:
          id: billing_full_name
          table: uc_orders
          field: billing_full_name
          relationship: uc_orders
          group_type: group
          admin_label: ''
          label: Name
          exclude: 0
          alter:
            alter_text: 0
            text: ''
            make_link: 0
            path: ''
            absolute: 0
            external: 0
            replace_spaces: 0
            path_case: none
            trim_whitespace: 0
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: 0
            max_length: ''
            word_boundary: 1
            ellipsis: 1
            more_link: 0
            more_link_text: ''
            more_link_path: ''
            strip_tags: 0
            trim: 0
            preserve_tags: ''
            html: 0
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: 1
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: 1
          empty: ''
          hide_empty: 0
          empty_zero: 0
          hide_alter_empty: 1
          link_to_user: 0
          format: first_last
          plugin_id: uc_order_full_name
          provider: uc_order
        primary_email:
          id: primary_email
          table: uc_orders
          field: primary_email
          relationship: uc_orders
          group_type: group
          admin_label: ''
          label: 'Email address'
          exclude: 0
          alter:
            alter_text: 0
            text: ''
            make_link: 0
            path: ''
            absolute: 0
            external: 0
            replace_spaces: 0
            path_case: none
            trim_whitespace: 0
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: 0
            max_length: ''
            word_boundary: 1
            ellipsis: 1
            more_link: 0
            more_link_text: ''
            more_link_path: ''
            strip_tags: 0
            trim: 0
            preserve_tags: ''
            html: 0
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: 1
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: 1
          empty: ''
          hide_empty: 0
          empty_zero: 0
          hide_alter_empty: 1
          link_to_user: mailto
          plugin_id: user_mail
          provider: user
        billing_city:
          id: billing_city
          table: uc_orders
          field: billing_city
          relationship: uc_orders
          group_type: group
          admin_label: ''
          label: Location
          exclude: 0
          alter:
            alter_text: 0
            text: ''
            make_link: 0
            path: ''
            absolute: 0
            external: 0
            replace_spaces: 0
            path_case: none
            trim_whitespace: 0
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: 0
            max_length: ''
            word_boundary: 1
            ellipsis: 1
            more_link: 0
            more_link_text: ''
            more_link_path: ''
            strip_tags: 0
            trim: 0
            preserve_tags: ''
            html: 0
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: 1
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: 1
          empty: ''
          hide_empty: 0
          empty_zero: 0
          hide_alter_empty: 1
          plugin_id: standard
          provider: views
        zone_code:
          id: zone_code
          table: billing_zones
          field: zone_code
          relationship: uc_orders
          group_type: group
          admin_label: ''
          label: ''
          exclude: 0
          alter:
            alter_text: 0
            text: ''
            make_link: 0
            path: ''
            absolute: 0
            external: 0
            replace_spaces: 0
            path_case: none
            trim_whitespace: 0
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: 0
            max_length: ''
            word_boundary: 1
            ellipsis: 1
            more_link: 0
            more_link_text: ''
            more_link_path: ''
            strip_tags: 0
            trim: 0
            preserve_tags: ''
            html: 0
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: false
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: 1
          empty: ''
          hide_empty: 0
          empty_zero: 0
          hide_alter_empty: 1
          plugin_id: standard
          provider: views
        country_name:
          id: country_name
          table: billing_countries
          field: country_name
          relationship: uc_orders
          group_type: group
          admin_label: ''
          label: ''
          exclude: 0
          alter:
            alter_text: 0
            text: ''
            make_link: 0
            path: ''
            absolute: 0
            external: 0
            replace_spaces: 0
            path_case: none
            trim_whitespace: 0
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: 0
            max_length: ''
            word_boundary: 1
            ellipsis: 1
            more_link: 0
            more_link_text: ''
            more_link_path: ''
            strip_tags: 0
            trim: 0
            preserve_tags: ''
            html: 0
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: false
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: 1
          empty: ''
          hide_empty: 0
          empty_zero: 0
          hide_alter_empty: 1
          plugin_id: standard
          provider: views
        order_id:
          id: order_id
          table: uc_orders
          field: order_id
          relationship: uc_orders
          group_type: count
          admin_label: ''
          label: Orders
          exclude: 0
          alter:
            alter_text: 0
            text: ''
            make_link: 0
            path: ''
            absolute: 0
            external: 0
            replace_spaces: 0
            path_case: none
            trim_whitespace: 0
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: 0
            max_length: ''
            word_boundary: 1
            ellipsis: 1
            more_link: 0
            more_link_text: ''
            more_link_path: ''
            strip_tags: 0
            trim: 0
            preserve_tags: ''
            html: 0
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: 1
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: 1
          empty: ''
          hide_empty: 0
          empty_zero: 0
          hide_alter_empty: 1
          link_to_order: 0
          plugin_id: uc_order
          provider: uc_order
        order_total:
          id: order_total
          table: uc_orders
          field: order_total
          relationship: uc_orders
          group_type: sum
          admin_label: ''
          label: Total
          exclude: 0
          alter:
            alter_text: 0
            text: ''
            make_link: 0
            path: ''
            absolute: 0
            external: 0
            replace_spaces: 0
            path_case: none
            trim_whitespace: 0
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: 0
            max_length: ''
            word_boundary: 1
            ellipsis: 1
            more_link: 0
            more_link_text: ''
            more_link_path: ''
            strip_tags: 0
            trim: 0
            preserve_tags: ''
            html: 0
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: 1
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: 1
          empty: ''
          hide_empty: 0
          empty_zero: 0
          hide_alter_empty: 1
          set_precision: false
          precision: 0
          decimal: .
          separator: ','
          format_plural: 0
          format_plural_singular: '1'
          format_plural_plural: '@count'
          prefix: ''
          suffix: ''
          format: uc_price
          plugin_id: uc_price
          provider: uc_store
      filters:
        uid_raw:
          id: uid_raw
          table: users
          field: uid_raw
          relationship: none
          group_type: group
          admin_label: ''
          operator: '!='
          value:
            min: ''
            max: ''
            value: '0'
          group: '1'
          exposed: false
          expose:
            operator_id: false
            label: ''
            description: ''
            use_operator: false
            operator: ''
            identifier: ''
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: 0
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          plugin_id: numeric
          provider: views
      sorts: {  }
      title: Customers
      header: {  }
      footer: {  }
      empty: {  }
      relationships:
        uc_orders:
          id: uc_orders
          table: users
          field: uc_orders
          relationship: none
          group_type: group
          admin_label: Orders
          required: 1
          plugin_id: standard
          provider: views
      arguments: {  }
      filter_groups:
        operator: AND
        groups: {  }
      group_by: 1
  page_1:
    display_plugin: page
    id: page_1
    display_title: Page
    position: 1
    display_options:
      path: admin/store/customers/view
      menu:
        type: normal
        title: 'View customers'
        description: 'View and search customer information.'
        name: admin
        weight: '-10'
        context: 0
label: uc_customers
module: views
id: uc_customers
tag: ''
uuid: de2c464f-17a0-40da-b000-ba0b0c558122
langcode: en
