uc_roles.settings:
  type: mapping
  label: 'Role settings'
  mapping:
    default_role:
      type: string
      label: ''
    default_role_choices:
      type: string
      label: ''
    default_by_quantity:
      type: boolean
      label: ''

    default_show_expiration:
      type: boolean
      label: ''
    default_end_expiration:
      type: string
      label: ''
    default_end_time:
      type: string
      label: ''
    default_expiration_header:
      type: string
      label: ''
    default_expiration_title:
      type: string
      label: ''
    default_expiration_message:
      type: string
      label: ''

    default_granularity:
      type: string
      label: ''
    default_length:
      type: string
      label: ''

    reminder_granularity:
      type: string
      label: ''
    reminder_length:
      type: string
      label: ''
